(function(){'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=t[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&r(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var da=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.R=b.prototype}function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function la(a){return ma(a,a)}
function ma(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function na(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.u=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}na.prototype.s=function(a){this.i=a};function pa(a,b){a.j={V:b,W:!0};a.g=a.u}na.prototype.return=function(a){this.j={return:a};this.g=this.u};function x(a,b,c){a.g=c;return{value:b}}function qa(a){this.g=new na;this.h=a}
function ra(a,b){oa(a.g);var c=a.g.h;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return z(a)}function sa(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(f){return a.g.h=null,pa(a.g,f),z(a)}a.g.h=null;d.call(a.g,h);return z(a)}
function z(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,pa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.W)throw b.V;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h.next,b,a.g.s):(a.g.s(b),b=z(a));return b};this.throw=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h["throw"],b,a.g.s):(pa(a.g,b),b=z(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function A(a){return ua(new ta(new qa(a)))}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.u=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var e=t.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.D),reject:f(this.l)}};b.prototype.D=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.G(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.C(f):this.s(f)}};
b.prototype.C=function(f){var g=void 0;try{g=f.then}catch(k){this.l(k);return}typeof g=="function"?this.K(g,f):this.s(f)};b.prototype.l=function(f){this.B(2,f)};b.prototype.s=function(f){this.B(1,f)};b.prototype.B=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.i=g;this.h===2&&this.F();this.I()};b.prototype.F=function(){var f=this;e(function(){if(f.J()){var g=t.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.J=
function(){if(this.u)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.I=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;b.prototype.G=
function(f){var g=this.j();f.L(g.resolve,g.reject)};b.prototype.K=function(f,g){var k=this.j();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(p,w){return typeof p=="function"?function(F){try{l(p(F))}catch(y){m(y)}}:w}var l,m,q=new b(function(p,w){l=p;m=w});this.L(k(f,l),k(g,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.L=function(f,g){function k(){switch(l.h){case 1:f(l.i);break;case 2:g(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?h.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=v(f),m=l.next();!m.done;m=l.next())d(m.value).L(g,k)})};b.all=function(f){var g=v(f),k=g.next();return k.done?d([]):new b(function(l,m){function q(F){return function(y){p[F]=y;w--;w==0&&l(p)}}var p=[],w=0;do p.push(void 0),w++,d(k.value).L(q(p.length-1),m),k=g.next();while(!k.done)})};return b});
function B(a,b){return Object.prototype.hasOwnProperty.call(a,b)}u("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});
u("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!B(k,f)){var l=new c;r(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!B(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&B(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&B(k,
f)&&B(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&B(k,f)&&B(k[f],this.g)?delete k[f][this.g]:!1};return b});
u("Map",function(a){function b(){var g={};return g.v=g.next=g.head=g}function c(g,k){var l=g[1];return ca(function(){if(l){for(;l.head!=g[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&B(g[0],l))for(g=0;g<m.length;g++){var q=m[g];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:g,m:q}}return{id:l,
list:m,index:-1,m:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=v(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(v([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(q){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.m?l.m.value=k:(l.m={next:this[1],v:this[1].v,head:this[1],key:g,value:k},l.list.push(l.m),this[1].v.next=l.m,this[1].v=l.m,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.m&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.m.v.next=g.m.next,g.m.next.v=g.m.v,g.m.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].v=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).m};e.prototype.get=function(g){return(g=d(this,g).m)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});u("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});
u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)B(b,d)&&c.push([d,b[d]]);return c}});u("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});u("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});
function wa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.entries",function(a){return a?a:function(){return wa(this,function(b,c){return[b,c]})}});u("globalThis",function(a){return a||t});u("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)B(b,d)&&c.push(b[d]);return c}});
u("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});u("Array.prototype.values",function(a){return a?a:function(){return wa(this,function(b,c){return c})}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var xa=xa||{},C=this||self;function ya(a,b){a=a.split(".");b=b||C;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function za(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function Aa(a){var b=za(a);return b=="array"||b=="object"&&typeof a.length=="number"}function D(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function Ba(a,b,c){return a.call.apply(a.bind,arguments)}
function Ca(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function Da(a,b,c){Da=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Ba:Ca;return Da.apply(null,arguments)}
function Ea(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.oa=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}};var Fa;function Ga(a){C.setTimeout(function(){throw a;},0)};var Ha,Ia=ya("CLOSURE_FLAGS"),Ja=Ia&&Ia[610401301];Ha=Ja!=null?Ja:!1;function Ka(){var a=C.navigator;return a&&(a=a.userAgent)?a:""}var E,La=C.navigator;E=La?La.userAgentData||null:null;function Ma(a){return Ha?E?E.brands.some(function(b){return(b=b.brand)&&b.indexOf(a)!=-1}):!1:!1}function G(a){return Ka().indexOf(a)!=-1};function H(){return Ha?!!E&&E.brands.length>0:!1}function Na(){return H()?Ma("Chromium"):(G("Chrome")||G("CriOS"))&&!(H()?0:G("Edge"))||G("Silk")};var Oa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Pa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Qa(a,b){b=Oa(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Ra(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Sa=H()?!1:G("Trident")||G("MSIE"),Ta=Ka().toLowerCase().indexOf("webkit")!=-1&&!G("Edge")&&G("Mobile");!G("Android")||Na();Na();G("Safari")&&(Na()||(H()?0:G("Coast"))||(H()?0:G("Opera"))||(H()?0:G("Edge"))||(H()?Ma("Microsoft Edge"):G("Edg/"))||H()&&Ma("Opera"));var Ua={},I=null;var Va=typeof Uint8Array!=="undefined",Wa=!Sa&&typeof btoa==="function";var Xa=typeof C.BigInt==="function"&&typeof C.BigInt(0)==="bigint";var Ya=Number.MIN_SAFE_INTEGER.toString(),Za=Xa?BigInt(Number.MIN_SAFE_INTEGER):void 0,$a=Number.MAX_SAFE_INTEGER.toString(),ab=Xa?BigInt(Number.MAX_SAFE_INTEGER):void 0;function bb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var J=typeof Symbol==="function"&&typeof Symbol()==="symbol";function cb(a){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?Symbol():a}var K=cb(),db=cb("2ex");var eb=Math.max,fb=eb.apply,gb=Object.values({ia:1,ga:2,fa:4,la:8,ka:16,ja:32,Z:64,na:128,ea:256,da:512,ha:1024,ba:2048,ma:4096,ca:8192,aa:16384}),hb;if(gb instanceof Array)hb=gb;else{for(var ib=v(gb),jb,kb=[];!(jb=ib.next()).done;)kb.push(jb.value);hb=kb}fb.call(eb,Math,hb);
var lb=J?function(a,b){a[K]|=b}:function(a,b){a.A!==void 0?a.A|=b:Object.defineProperties(a,{A:{value:b,configurable:!0,writable:!0,enumerable:!1}})},L=J?function(a){return a[K]|0}:function(a){return a.A|0},M=J?function(a){return a[K]}:function(a){return a.A},N=J?function(a,b){a[K]=b}:function(a,b){a.A!==void 0?a.A=b:Object.defineProperties(a,{A:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function mb(a,b){N(b,(a|0)&-30975)}function nb(a,b){N(b,(a|34)&-30941)};var O={},ob={};function pb(a){return!(!a||typeof a!=="object"||a.g!==ob)}function qb(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)&&a.constructor===Object}function P(a){return!Array.isArray(a)||a.length?!1:L(a)&1?!0:!1};var rb;function sb(a){return a.displayName||a.name||"unknown type name"};var tb;function ub(a,b){tb=b;a=new a(b);tb=void 0;return a}
function vb(a,b,c){var d=d!=null?d:0;a==null&&(a=tb);tb=void 0;if(a==null){var e=96;c?(a=[c],e|=512):a=[];b&&(e=e&-33521665|(b&1023)<<15)}else{if(!Array.isArray(a))throw Error("narr");e=L(a);if(e&2048)throw Error("farr");if(e&64)return a;d===1||d===2||(e|=64);if(c&&(e|=512,c!==a[0]))throw Error("mid");a:{c=a;if(d=c.length){var h=d-1;if(qb(c[h])){e|=256;b=h-(+!!(e&512)-1);if(b>=1024)throw Error("pvtlmt");e=e&-33521665|(b&1023)<<15;break a}}if(b){b=Math.max(b,d-(+!!(e&512)-1));if(b>1024)throw Error("spvt");
e=e&-33521665|(b&1023)<<15}}}N(a,e);return a};function wb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "bigint":return(Xa?a>=Za&&a<=ab:a[0]==="-"?bb(a,Ya):bb(a,$a))?Number(a):String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(P(a))return}else if(Va&&a!=null&&a instanceof Uint8Array){if(Wa){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{b===void 0&&(b=0);if(!I){I={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");
d=["+/=","+/","-_=","-_.","-_"];for(var e=0;e<5;e++){var h=c.concat(d[e].split(""));Ua[e]=h;for(var f=0;f<h.length;f++){var g=h[f];I[g]===void 0&&(I[g]=f)}}}b=Ua[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=h=0;h<a.length-2;h+=3){var k=a[h],l=a[h+1];g=a[h+2];f=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[e++]=""+f+k+l+g}f=0;g=d;switch(a.length-h){case 2:f=a[h+1],g=b[(f&15)<<2]||d;case 1:a=a[h],c[e]=""+b[a>>2]+b[(a&3)<<4|f>>4]+g+d}a=c.join("")}return a}}return a};function xb(a,b,c){a=Array.prototype.slice.call(a);var d=a.length,e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var h in e)b[h]=c(e[h])}return a}function yb(a,b,c,d,e){if(a!=null){if(Array.isArray(a))a=P(a)?void 0:e&&L(a)&2?a:zb(a,b,c,d!==void 0,e);else if(qb(a)){var h={},f;for(f in a)h[f]=yb(a[f],b,c,d,e);a=h}else a=b(a,d);return a}}
function zb(a,b,c,d,e){var h=d||c?L(a):0;d=d?!!(h&32):void 0;a=Array.prototype.slice.call(a);for(var f=0;f<a.length;f++)a[f]=yb(a[f],b,c,d,e);c&&c(h,a);return a}function Ab(a){return a.P===O?a.toJSON():wb(a)};function Bb(a,b,c){c=c===void 0?nb:c;if(a!=null){if(Va&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=L(a);if(d&2)return a;b&&(b=d===0||!!(d&32)&&!(d&64||!(d&16)));return b?(N(a,(d|34)&-12293),a):zb(a,Bb,d&4?nb:c,!0,!0)}a.P===O&&(c=a.o,d=M(c),a=d&2?a:ub(a.constructor,Cb(c,d,!0)));return a}}function Cb(a,b,c){var d=c||b&2?nb:mb,e=!!(b&32);a=xb(a,b,function(h){return Bb(h,e,d)});lb(a,32|(c?2:0));return a};function Db(a,b,c,d){b=d+(+!!(b&512)-1);if(!(b<0||b>=a.length||b>=c))return a[b]}
function Eb(a,b,c,d){if(c===-1)return null;var e=b>>15&1023||536870912;if(c>=e){if(b&256)return a[a.length-1][c]}else{var h=a.length;if(d&&b&256&&(d=a[h-1][c],d!=null)){if(Db(a,b,e,c)&&db!=null){var f;a=(f=rb)!=null?f:rb={};f=a[db]||0;f>=4||(a[db]=f+1,f=Error(),f.__closure__error__context__984382||(f.__closure__error__context__984382={}),f.__closure__error__context__984382.severity="incident",Ga(f))}return d}return Db(a,b,e,c)}}
function Fb(a,b,c,d){var e=b>>15&1023||536870912;if(c>=e){var h=b;if(b&256)var f=a[a.length-1];else{if(d==null)return;f=a[e+(+!!(b&512)-1)]={};h|=256}f[c]=d;c<e&&(a[c+(+!!(b&512)-1)]=void 0);h!==b&&N(a,h)}else a[c+(+!!(b&512)-1)]=d,b&256&&(a=a[a.length-1],c in a&&delete a[c])}function Q(a,b){var c=c===void 0?!1:c;a=a.o;b=Eb(a,M(a),b);b=b==null||typeof b==="boolean"?b:typeof b==="number"?!!b:void 0;return b!=null?b:c}
function R(a,b,c){if(c!=null&&typeof c!=="boolean")throw Error("Expected boolean but got "+za(c)+": "+c);var d=a.o,e=M(d);if(e&2)throw Error();Fb(d,e,b,c===!1?void 0:c);return a};var Gb;function S(a,b,c){this.o=vb(a,b,c)}S.prototype.toJSON=function(){return Hb(this)};S.prototype.P=O;S.prototype.toString=function(){try{return Gb=!0,Hb(this).toString()}finally{Gb=!1}};
function Hb(a){a=Gb?a.o:zb(a.o,Ab,void 0,void 0,!1);var b=!Gb,c=a.length;if(c){var d=a[c-1],e=qb(d);e?c--:d=void 0;var h=a;if(e){b:{var f=d;var g;var k=!1;if(f)for(var l in f)if(isNaN(+l))e=void 0,((e=g)!=null?e:g={})[l]=f[l];else if(e=f[l],Array.isArray(e)&&(P(e)||pb(e)&&e.size===0)&&(e=null),e==null&&(k=!0),e!=null){var m=void 0;((m=g)!=null?m:g={})[l]=e}k||(g=f);if(g)for(var q in g){k=g;break b}k=null}f=k==null?d!=null:k!==d}for(;c>0;c--){g=h[c-1];if(!(g==null||P(g)||pb(g)&&g.size===0))break;var p=
!0}if(h!==a||f||p){if(!b)h=Array.prototype.slice.call(h,0,c);else if(p||f||k)h.length=c;k&&h.push(k)}p=h}else p=a;return p};var Ib=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function T(){this.l=this.l;this.u=this.u}T.prototype.l=!1;T.prototype.isDisposed=function(){return this.l};T.prototype.dispose=function(){this.l||(this.l=!0,this.H())};T.prototype[Symbol.dispose]=function(){this.dispose()};T.prototype.H=function(){if(this.u)for(;this.u.length;)this.u.shift()()};var Jb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Kb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Jb.length;h++)c=Jb[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Lb=globalThis.trustedTypes,Mb;function Nb(){var a=null;if(!Lb)return a;try{var b=function(c){return c};a=Lb.createPolicy("uf-api#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function Ob(a){this.g=a}Ob.prototype.toString=function(){return this.g+""};function Pb(a){Mb===void 0&&(Mb=Nb());var b=Mb;return new Ob(b?b.createScriptURL(a):a)};var Qb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Rb(a,b){b=Qb.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)}function Sb(a){a=a===void 0?document:a;var b,c;a=(c=(b="document"in a?a.document:a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};function Tb(a,b){if(b instanceof Ob)b=b.g;else throw Error("");a.src=b;(b=Sb(a.ownerDocument&&a.ownerDocument.defaultView||window))&&a.setAttribute("nonce",b)};function Ub(a){var b=va.apply(1,arguments);if(b.length===0)return Pb(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Pb(c)};function Vb(a,b,c){function d(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var h=c[e];if(!Aa(h)||D(h)&&h.nodeType>0)d(h);else{a:{if(h&&typeof h.length=="number"){if(D(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}Pa(f?Ra(h):h,d)}}}function Wb(a){var b="SCRIPT";a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function Xb(a){this.g=a||C.document||document}Xb.prototype.append=function(a,b){Vb(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments)};function Yb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var Zb="closure_listenable_"+(Math.random()*1E6|0);var $b=0;function ac(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.O=e;this.key=++$b;this.M=this.N=!1}function bc(a){a.M=!0;a.listener=null;a.proxy=null;a.src=null;a.O=null};function cc(a){this.src=a;this.g={};this.h=0}cc.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var f=dc(a,b,d,e);f>-1?(b=a[f],c||(b.N=!1)):(b=new ac(b,this.src,h,!!d,e),b.N=c,a.push(b));return b};function ec(a,b){var c=b.type;c in a.g&&Qa(a.g[c],b)&&(bc(b),a.g[c].length==0&&(delete a.g[c],a.h--))}function dc(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.M&&h.listener==b&&h.capture==!!c&&h.O==d)return e}return-1};var fc="closure_lm_"+(Math.random()*1E6|0),gc={},hc=0;
function ic(a,b,c,d,e){if(Array.isArray(b))for(var h=0;h<b.length;h++)ic(a,b[h],c,d,e);else(d=D(d)?!!d.capture:!!d,c=jc(c),a&&a[Zb])?(a=a.i,b=String(b).toString(),b in a.g&&(h=a.g[b],c=dc(h,c,d,e),c>-1&&(bc(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.g[b],a.h--)))):a&&(a=kc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=dc(b,c,d,e)),(c=a>-1?b[a]:null)&&typeof c!=="number"&&c&&!c.M&&((e=c.src)&&e[Zb]?ec(e.i,c):(d=c.type,b=c.proxy,e.removeEventListener?e.removeEventListener(d,b,c.capture):
e.detachEvent?e.detachEvent(d in gc?gc[d]:gc[d]="on"+d,b):e.addListener&&e.removeListener&&e.removeListener(b),hc--,(d=kc(e))?(ec(d,c),d.h==0&&(d.src=null,e[fc]=null)):bc(c))))}function kc(a){a=a[fc];return a instanceof cc?a:null}var lc="__closure_events_fn_"+(Math.random()*1E9>>>0);function jc(a){if(typeof a==="function")return a;a[lc]||(a[lc]=function(b){return a.handleEvent(b)});return a[lc]};function U(){T.call(this);this.i=new cc(this);this.T=this;this.D=null}Ea(U,T);U.prototype[Zb]=!0;U.prototype.removeEventListener=function(a,b,c,d){ic(this,a,b,c,d)};
function V(a,b){var c=a.D;if(c){var d=[];for(var e=1;c;c=c.D)d.push(c),++e}a=a.T;c=b.type||b;typeof b==="string"?b=new Yb(b,a):b instanceof Yb?b.target=b.target||a:(e=b,b=new Yb(c,a),Kb(b,e));e=!0;var h;if(d)for(h=d.length-1;h>=0;h--){var f=b.g=d[h];e=mc(f,c,!0,b)&&e}f=b.g=a;e=mc(f,c,!0,b)&&e;e=mc(f,c,!1,b)&&e;if(d)for(h=0;h<d.length;h++)f=b.g=d[h],e=mc(f,c,!1,b)&&e}
U.prototype.H=function(){U.R.H.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,bc(d[e]);delete a.g[c];a.h--}}this.D=null};function mc(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.M&&f.capture==c){var g=f.listener,k=f.O||f.src;f.N&&ec(a.i,f);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function nc(a){try{return C.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var oc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function pc(){U.call(this);this.headers=new Map;this.h=!1;this.g=null;this.C="";this.j=this.J=this.s=this.I=!1;this.F=0;this.B=null;this.K="";this.G=!1}Ea(pc,U);var qc=/^https?$/i,rc=["POST","PUT"],sc=[];function tc(a,b){var c=new pc;sc.push(c);b&&c.i.add("complete",b,!1,void 0,void 0);c.i.add("ready",c.U,!0,void 0,void 0);c.F=2E3;c.G=!0;uc(c,a)}n=pc.prototype;n.U=function(){this.dispose();Qa(sc,this)};
function uc(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.C+"; newUri="+b);a.C=b;a.I=!1;a.h=!0;a.g=new XMLHttpRequest;a.g.onreadystatechange=Ib(Da(a.S,a));try{a.J=!0,a.g.open("GET",String(b),!0),a.J=!1}catch(h){vc(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var d in c)b.set(d,c[d]);else if(typeof c.keys==="function"&&typeof c.get==="function"){d=v(c.keys());for(var e=d.next();!e.done;e=d.next())e=e.value,b.set(e,
c.get(e))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(h){return"content-type"==h.toLowerCase()});d=C.FormData&&!1;!(Oa(rc,"GET")>=0)||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=v(b);for(c=b.next();!c.done;c=b.next())d=v(c.value),c=d.next().value,d=d.next().value,a.g.setRequestHeader(c,d);a.K&&(a.g.responseType=a.K);"withCredentials"in a.g&&a.g.withCredentials!==a.G&&(a.g.withCredentials=a.G);try{wc(a),
a.F>0&&(a.B=setTimeout(a.Y.bind(a),a.F)),a.s=!0,a.g.send(""),a.s=!1}catch(h){vc(a)}}n.Y=function(){typeof xa!="undefined"&&this.g&&(V(this,"timeout"),this.abort(8))};function vc(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);xc(a);yc(a)}function xc(a){a.I||(a.I=!0,V(a,"complete"),V(a,"error"))}n.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,V(this,"complete"),V(this,"abort"),yc(this))};
n.H=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),yc(this,!0));pc.R.H.call(this)};n.S=function(){this.isDisposed()||(this.J||this.s||this.j?zc(this):this.X())};n.X=function(){zc(this)};
function zc(a){if(a.h&&typeof xa!="undefined")if(a.s&&(a.g?a.g.readyState:0)==4)setTimeout(a.S.bind(a),0);else if(V(a,"readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{try{var b=(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(f){b=-1}a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var h=String(a.C).match(oc)[1]||null;!h&&C.self&&C.self.location&&(h=C.self.location.protocol.slice(0,-1));e=!qc.test(h?h.toLowerCase():
"")}d=e}d?(V(a,"complete"),V(a,"success")):xc(a)}finally{yc(a)}}}function yc(a,b){if(a.g){wc(a);var c=a.g;a.g=null;b||V(a,"ready");try{c.onreadystatechange=null}catch(d){}}}function wc(a){a.B&&(clearTimeout(a.B),a.B=null)}n.isActive=function(){return!!this.g};function W(a){this.o=vb(a)}ka(W,S);n=W.prototype;n.getEnableSsEngine=function(){return Q(this,2)};n.getEnableAwr=function(){return Q(this,3)};n.getAlohaAutoGaRollout=function(){return Q(this,5)};n.getEnableConfigurator=function(){return Q(this,6)};n.getEnableMweb=function(){return Q(this,7)};n.getEnableCtlConsentCheckbox=function(){return Q(this,8)};n.getEnableIframe=function(){return Q(this,9)};n.getEnableScreenshotNudge=function(){return Q(this,10)};
n.getEnableWebStartupConfigEndpoint=function(){return Q(this,11)};n.getEnableJunkNudge=function(){return Q(this,12)};n.getEnableConfiguratorLocale=function(){return Q(this,13)};n.getEnableTinyNoPointer=function(){return Q(this,14)};n.getEnableSupportSessionLogging=function(){return Q(this,15)};n.getEnableFileUploadForScreenshot=function(){return Q(this,16)};n.getEnableDirectDeflectionForSingleCategory=function(){return Q(this,17)};n.getEnableImageSanitization=function(){return Q(this,18)};
n.getEnableAlohaBinarySplit=function(){return Q(this,19)};n.getEnableDbFeedbackIntents=function(){return Q(this,20)};n.getEnableMarkMandatoryFieldsWithRequired=function(){return Q(this,21)};n.getEnableFeedbackCategoryCustomUi=function(){return Q(this,22)};n.getEnableRealtimeCtl=function(){return Q(this,23)};function Ac(a){this.o=vb(a)}ka(Ac,S);function Bc(a){return Cc.some(function(b){return b.test(a)})}var Cc=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var Dc="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");var Ec=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),Fc=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
function Gc(a,b){var c;var d=(c=a.formContent)==null?void 0:c.locale;c=d==null?void 0:d.split("-")[0];d=d&&Dc.includes(d)?d:c&&Dc.includes(c)?c:void 0;d=(d!=null?d:"en").replaceAll("-","_").toLowerCase();var e;a=((e=a.initializationData)==null?0:e.useNightlyRelease)?"nightly":"live";var h;return(b==null?0:(h=b.getEnableAlohaBinarySplit)==null?0:h.call(b))?Ub(Ec,a):Ub(Fc,a,d)};var Hc,Ic;function Jc(a,b,c,d){if(Hc)return Hc;var e=Gc(a,d);return Hc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Wb(document);Tb(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+e.toString())};c.body.appendChild(g)})}
function Kc(a,b,c,d){if(Ic)return Ic;var e=Gc(a,d);return Ic=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Wb(document);Tb(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+e.toString())};c.body.appendChild(g)})}
function Lc(a,b,c,d,e){e=e===void 0?!0:e;var h,f,g,k,l;return A(function(m){switch(m.g){case 1:return h=Date.now(),x(m,Jc(a,c,d,b),2);case 2:f=m.i;if(!(e||((k=a.initializationData)==null?0:k.useNightlyRelease)||((l=a.initializationData)==null?0:l.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);m.g=3;break}return x(m,f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=m.i;case 3:return g.initiateAloha(),m.return(g)}})}
function Mc(a,b,c,d){var e,h,f;return A(function(g){if(g.g==1)return e=Date.now(),x(g,Kc(a,c,d.document,b),2);if(g.g!=3)return h=g.i,x(g,h.initializeFeedbackClientAsync(a,e,b,d),3);f=g.i;f.initiateAloha();return g.return(f)})}
function Nc(a,b,c){var d=!0;d=d===void 0?!0:d;var e,h,f,g,k,l,m,q,p,w;return A(function(F){e=c||C;if((h=b)==null?0:(g=(f=h).getEnableAlohaBinarySplit)==null?0:g.call(f)){k=e;if(k.isFormOpened)throw l=Error("Form is either loading or already opened"),l.name="DuplicateFormError",l;k.isFormOpened=!0;a.callbacks=a.callbacks||{};m=a.callbacks.onClose||function(){};a.callbacks.onClose=function(y){k.isFormOpened=!1;m(y)};try{return F.return(Mc(a,b,k,e))}catch(y){throw k.isFormOpened=!1,y;}}else{q=e;if(q.isFormOpened)throw p=
Error("Form is either loading or already opened"),p.name="DuplicateFormError",p;q.isFormOpened=!0;a.callbacks=a.callbacks||{};w=a.callbacks.onClose||function(){};a.callbacks.onClose=function(y){q.isFormOpened=!1;w(y)};try{return F.return(Lc(a,b,q,e.document,d))}catch(y){throw q.isFormOpened=!1,y;}}F.g=0})};function Oc(a,b){return A(function(c){return c.return(new Promise(function(d){var e=Pc(b!=null?b:"")+"/aloha_form_properties?productId="+a;tc(e,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.g){var l=f.g.responseText;l.indexOf(")]}'\n")==0&&(l=l.substring(5));b:{if(C.JSON)try{var m=C.JSON.parse(l);break b}catch(w){}m=nc(l)}}else m=void 0;var q=k.call(g,m);if(q==null||q=="")h=new Ac;else{var p=JSON.parse(q);if(!Array.isArray(p))throw Error("dnarr");lb(p,32);h=ub(Ac,p)}}catch(w){k=
new Ac;m=new W;m=R(m,5,!0);m=R(m,2,!0);m=R(m,4,!1);m=R(m,8,!0);m=R(m,9,!0);m=R(m,7,!0);m=R(m,10,!0);m=R(m,12,!0);m=R(m,13,!1);m=R(m,14,!0);m=R(m,15,!0);m=R(m,20,!1);if(m!=null){if(!(m instanceof W))throw Error("Expected instanceof "+sb(W)+" but got "+(m&&sb(m.constructor)));}else m=void 0;q=k.o;p=M(q);if(p&2)throw Error();Fb(q,p,1,m);h=k}d(h)})}))})}function Pc(a){return Bc(a)?a:"https://www.google.com/tools/feedback"};function Qc(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||C,e=d.document,h=a.nonce||Sb(d);h&&!a.nonce&&(a.nonce=h);if(a.flow=="help"){var f=ya("document.location.href",d);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var g=JSON.stringify(b);(f=g.length<=1200)&&(a.psdJson=g)}f||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=d.GOOGLE_FEEDBACK_START)f.apply(d,
b);else{d=c+"/load.js?";for(var k in a)b=a[k],b==null||D(b)||(d+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=e?new Xb(e.nodeType==9?e:e.ownerDocument||e.document):Fa||(Fa=new Xb);a=Wb(a.g);h&&a.setAttribute("nonce",h);h=Pb(d);Tb(a,h);e.body.appendChild(a)}}
function Rc(a,b,c,d){var e,h;A(function(f){e=c||C;var g=a.serverEnvironment==="DEV",k=c||C;k=a.nonce||Sb(k);g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,pa:void 0,defaultFormInputValues:void 0,
defaultFormInputValuesString:void 0,abuseLink:a.abuseLink,additionalDataConsent:a.additionalDataConsent},initializationData:{isLocalServer:g,nonce:k,useNightlyRelease:g,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(k=new Map(Object.entries(b)),g.extraData.productSpecificData=k);h=g;return x(f,Nc(h,d,e),0)})}
function Sc(a,b,c){try{if(a.flow==="help"){var d=a.helpCenterPath.replace(/^\//,"");Rb(c||window,"https://support.google.com/"+d)}else a.flow==="submit"?Qc(a,b,c):Oc(a.productId,a.feedbackServerUri).then(function(e){var h=e.o;var f=M(h),g=Eb(h,f,1,!1);if(g!=null&&typeof g==="object"&&g.P===O)var k=g;else if(Array.isArray(g)){var l=k=L(g);l===0&&(l|=f&32);l|=f&2;l!==k&&N(g,l);k=new W(g)}else k=void 0;k!==g&&k!=null&&Fb(h,f,1,k);h=k;h!=null&&(e=e.o,f=M(e),f&2||(g=h,k=g.o,l=M(k),g=l&2?ub(g.constructor,
Cb(k,l,!1)):g,g!==h&&(h=g,Fb(e,f,1,h))));e=h;h=!Ta||(e==null?void 0:e.getEnableMweb());f=!a.tinyNoPointer||(e==null?void 0:e.getEnableTinyNoPointer());!e||e.getAlohaAutoGaRollout()&&h&&f?Rc(a,b,c,e):Qc(a,b,c)},function(e){e&&e.name!=="DuplicateFormError"&&Qc(a,b,c)})}catch(e){Rc(a,b,c,null)}}var X=["userfeedback","api","startFeedback"],Y=C;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||Sc===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Sc;}).call(this);
